openapi: 3.1.0
info:
  version: 1.0.0
  title: NodeJS GoIT API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of NodeJS GoIT API
tags:
  - name: Users
    description: Operations about users.
  - name: Auth
    description: Auth operations.
  - name: Credit Cards
    description: Credit card operations.
  - name: Balance
    description: Balance operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer